### PR TITLE
handle errors in formula cells

### PR DESCRIPTION
**Pull request by cristichircu**
fix for https://github.com/crealytics/spark-excel/issues/587

For v1 the previous behavior is changed and, instead of the formula, this will return null if setErrorCellsToFallbackValues == false and "" if setErrorCellsToFallbackValues == true
For v2, if useNullForErrorCells == false this maintains the current behavior, returning the formula, and returns null if useNullForErrorCells == true
I would propose to also change [this line](https://github.com/crealytics/spark-excel/blob/935a9494a2dbe15f181b6c55f0efaaf43773e2b4/src/main/scala/com/crealytics/spark/v2/excel/ExcelHelper.scala#L86) to return "" in case of error for string formula to keep this consistent with v1. Not sure why anyone would want to see the formula.

### CODE REVIEW

**Comment by cristichircu** [comment]
because of the change in default behavior for v1 the tests in com.crealytics.spark.excel.PlainNumberReadSuite are currently failing. I would argue that this is the correct behavior, but I get that this might be a breaking change for someone that used it like this up to now.
Any pointers about the desired behavior would be appreciated.
Thanks!

**Comment by nightscape** [comment]
Hey @cristichircu, this looks reasonable to me. I don't have time to do a more thorough review, but if noone objects, I'd be happy to merge it after you have updated com.crealytics.spark.excel.PlainNumberReadSuite.
@quanghgx @christianknoepfle opinions?

**Comment by cristichircu** [comment]
Had another look at how error formulas for string columns were handled in v2. In the current version the formula generating the error was returned. I updated it to return the error value, to make it consistent with errors on string columns and what users see in excel (please check the test change for an example).
@quanghgx any reason why you chose to implement the 'useNullForErrorCells' option and return the error values instead of implementing the 'setErrorCellsToFallbackValues' option and returning default values?

**Comment by cristichircu** [comment]
@quanghgx @nightscape Anything I can help with to get this merged?

**Comment by nightscape** [comment]
Yes, a ping 😄 
Merging now 👍

**Comment by cristichircu** [comment]
:) Thank you, @nightscape !

**Pull request merged**
