### PR TITLE
add more classes to fat jar that poi needs and don't shade poi classes

### PR DESCRIPTION
**Pull request by pjfanning**
replaces #597

### CODE REVIEW

**Comment by nightscape** [comment]
@pjfanning I got the CI publishing step to work again 🎉 
I just rebased this branch on the working `main` branch and released it as `0.18.0-beta2`.
It would be nice if someone could try this out.

**Comment by pjfanning** [comment]
@nightscape I tried the 0.18.0-beta2 jar in Databricks Community edition and it seemed to work ok.

**Comment by nightscape** [comment]
@pjfanning shall we give people a few more days for providing feedback, or would you vote for releasing asap?

**Comment by pjfanning** [comment]
@nightscape I think it's best to allow a few more days for testing.

**Comment by nightscape** [comment]
Still looking good 😃 
I'd give it a shot now and release it as 0.18.0.

**Pull request merged**
