### PR TITLE
Support ERROR cell type when using inferSchema=true

### LINKED ISSUE #208: Scala Match Error
I have 2 excel sheets (same format, same schema) that I am converting to a dataframe. The first excel sheet loaded perfectly fine. Both excel sheets contain blanks cells, and I have inferschema set to true. However, I get this error below when I try to load the second excel sheet. 

Not sure if there is something wrong with one row -- is there a way to tell which row or column the error in the data is happening? 

`scala.MatchError: ERROR (of class shadeio.poi.ss.usermodel.CellType)`

`at com.crealytics.spark.excel.ExcelRelation.com$crealytics$spark$excel$ExcelRelation$$getSparkType(ExcelRelation.scala:84)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7$$anonfun$9$$anonfun$apply$7$$anonfun$apply$9.apply(ExcelRelation.scala:110)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7$$anonfun$9$$anonfun$apply$7$$anonfun$apply$9.apply(ExcelRelation.scala:110)
	at scala.Option.map(Option.scala:146)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7$$anonfun$9$$anonfun$apply$7.apply(ExcelRelation.scala:110)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7$$anonfun$9$$anonfun$apply$7.apply(ExcelRelation.scala:110)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7$$anonfun$9.apply(ExcelRelation.scala:110)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7$$anonfun$9.apply(ExcelRelation.scala:109)
	at scala.collection.immutable.List.map(List.scala:284)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7.apply(ExcelRelation.scala:109)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$7.apply(ExcelRelation.scala:105)
	at scala.Option.getOrElse(Option.scala:121)
	at com.crealytics.spark.excel.ExcelRelation.headerColumns$lzycompute(ExcelRelation.scala:105)
	at com.crealytics.spark.excel.ExcelRelation.headerColumns(ExcelRelation.scala:104)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:162)
	at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:161)
	at scala.Option.getOrElse(Option.scala:121)
	at com.crealytics.spark.excel.ExcelRelation.inferSchema(ExcelRelation.scala:161)
	at com.crealytics.spark.excel.ExcelRelation.<init>(ExcelRelation.scala:35)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:40)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:18)
	at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:12)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:347)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:307)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:293)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:214)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$anonfun$1$$anonfun$apply$1.apply(command-4306809369424782:22)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$anonfun$1$$anonfun$apply$1.apply(command-4306809369424782:7)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$anonfun$1.apply(command-4306809369424782:7)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$anonfun$1.apply(command-4306809369424782:5)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:5)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:100)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:102)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:104)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:106)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:108)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:110)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:112)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw$$iw.<init>(command-4306809369424782:114)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw$$iw.<init>(command-4306809369424782:116)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw$$iw.<init>(command-4306809369424782:118)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$$iw.<init>(command-4306809369424782:120)
	at linefbdb2b3d70b8425092601e89614a415a106.$read.<init>(command-4306809369424782:122)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$.<init>(command-4306809369424782:126)
	at linefbdb2b3d70b8425092601e89614a415a106.$read$.<clinit>(command-4306809369424782)
	at linefbdb2b3d70b8425092601e89614a415a106.$eval$.$print$lzycompute(<notebook>:7)
	at linefbdb2b3d70b8425092601e89614a415a106.$eval$.$print(<notebook>:6)
	at linefbdb2b3d70b8425092601e89614a415a106.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:215)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:700)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:653)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$9.apply(DriverLocal.scala:386)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$9.apply(DriverLocal.scala:363)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:235)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:230)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:49)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:272)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:49)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:363)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:639)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:485)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:597)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:390)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)`

* Spark version and language Scala 2.11, Spark 2.4.4
* Spark-Excel version: com.crealytics:spark-excel_2.11:0.12.4
* Operating System and version, cluster environment: Databricks Runtime 6.1, Standard Cluster Mode

Worker Type:
14.0 GB Memory, 4 Cores, 0.75 DBU
Standard_DS3_v2
Min Workers: 2 Max Workers: 8

Driver Type:
14.0 GB Memory, 4 Cores, 0.75 DBU
Standard_DS3_v2

### PR DESCRIPTION
**Pull request by derianpt**
Fixes #208 

When using `inferSchema` option, and the excel file we are reading has `ERROR` type cells, we will have a runtime error: 
`scala.MatchError: ERROR (of class shadeio.poi.ss.usermodel.CellType)` 

This PR adds support to have the option of treating ERROR cells as string cells and outputting the error messages instead (e.g. `#N/A`, `#NULL!`)

### CODE REVIEW

**Comment by derianpt** [comment]
@nightscape I'm afraid it's not possible to individually set `ERROR` cells as `null` due to the following reasons: 
1. Other cells for the same column might have valid values (non ERROR) 
2. If we set the type of that cell to NullType, the `InferSchema.apply` function will still finalise the type of the entire column as `StringType` after merging.  

Please see the commented out test case for more info. Appreciate if you have any idea on how to output individual `ERROR` cells as `null`. 

If it's not possible, we can just go with the default behaviour of processing `ERROR` cells as strings, which will at least prevent the runtime error & adds support for them.

**Comment by nightscape** [comment]
@derianpt overall great job!
I didn't find the time to check the tests yet, will hopefully get to it this weekend or early next week.

**Comment by derianpt** [comment]
> @derianpt overall great job!
> I didn't find the time to check the tests yet, will hopefully get to it this weekend or early next week.

Hi @nightscape, have you had the time to check out the tests yet? 🙇

**Comment by nightscape** [comment]
I just had a look. I think the problem is that the second column in your example xlsx file contains only errors.
If you put in another row with e.g. a double value the schema should be inferred correctly.

**Comment by derianpt** [comment]
Thanks for the tip @nightscape. Turns out I was missing the code change to update how cell values should being extracted for `ERROR` cell types. The tests are now passing. 

However, there is a side effect when we treat errors as strings: the entire column will then be interpreted as string type. Understandable and acceptable behaviour imo. This is reflected in the first test case.

I've also put a note of this in the README.

**Comment by nightscape** [comment]
If I understand correctly, the type of the column changes to String only if there is an error in that column, and then only if it is within the first `excerptSize` rows which are used for schema inference.
If an error happens somewhere after `excerptSize` rows it would probably fail at runtime because the column was inferred to be e.g. `Double` type from the error-free first rows and then the error string can't be converted into a `Double`.
I've read up a little on how error handling is done in other Spark datasources, and their approach is to have different error handling modes (`Permissive`, `Fail Fast`, `Drop Malformed`). In `Permissive` mode, bad records are stored in a `__corrupt_record` column. I'm wondering if we should apply the same strategy here?

**Comment by derianpt** [comment]
>If I understand correctly, the type of the column changes to String only if there is an error in that column, and then only if it is within the first excerptSize rows which are used for schema inference.
If an error happens somewhere after `excerptSize` rows it would probably fail at runtime because the column was inferred to be e.g. Double type from the error-free first rows and then the error string can't be converted into a Double.

I have modified the test file & confirmed this behaviour. Looks like blanket converting to String will not work, we need to conform to the inferred column type. However, setting as `null` still works. 

I suggest this strategy; 
By default, we convert `ERROR` cells to `null`, but we have a boolean option `setErrorCellsToFallbackValues`: 

`.option("setErrorCellsToFallbackValues", "true") // Optional, default: false, where errors will be converted to null. If true, any ERROR cell values (e.g. #N/A) will be converted to the zero values of the column's data type.`

For the sensible fallback values, we can refer to the range of values defined in [spark docs](https://spark.apache.org/docs/2.4.0/sql-reference.html#data-types)

This is similar to `PERMISSIVE` mode but less complex to implement + we won't need metadata.

**Comment by nightscape** [comment]
Looks good! I'll merge once it's ready from your side 👍

**Comment by derianpt** [comment]
Yup PR is ready to be merged from my side

**Comment by nightscape** [comment]
Hi @derianpt, great job!
Would you be interested in become a project contributor?

**Comment by derianpt** [comment]
Sure @nightscape

**Comment by derianpt** [comment]
@nightscape Could I trouble you to release a new version with this fix? I would like to use it in my app 🙇

**Comment by nightscape** [comment]
I just fixed the SNAPSHOT release mechanism, so every commit to main gets a release.
The newest one is `0.13.6+11-1eaf2896-SNAPSHOT` which contains your changes.

I would also like to add you as contributor to the project, then you could create a `0.13.7` release.
Do you have 2FA enabled on your account?

**Comment by derianpt** [comment]
Yes I have 2FA enabled.

**Pull request merged**
