### PR TITLE
Added support for FORMULA cells when typing to String or Numeric types

### PR DESCRIPTION
**Pull request by habelson**
Pull Request to support issue #30 . This patch will work in most cases where cached values exist in the saved worksheet. I was not able to add support for typing other than String or Numeric, perhaps someone else can embellish.

### CODE REVIEW

**Comment by nightscape** [comment]
Out of interest: Could you also [evaluate the cells](https://poi.apache.org/spreadsheet/eval.html) if no cached value exists?

**Comment by habelson** [comment]
@nightscape I do not think that apache poi has support for that. That would require duplicating the excel formulas engine in the library which i think would be far outside the scope of this plugin.

**Comment by nightscape** [comment]
Yeah, that would probably be the best option.
Would you mind adding that?
If not, I'm also OK with merging it as is.

**Comment by litzebauer** [comment]
@nightscape Any chance you can merge this change in?

**Comment by nightscape** [comment]
I just rebased this PR and released it as 0.9.9. It will probably take a few hours until it is available via Sonatype.
Could you give it a whirl and report back here in case there are problems?

**Pull request closed without merging**
