### PR TITLE
add more classes to fat jar that poi needs and don't shade poi classes

### PR DESCRIPTION
**Pull request by pjfanning**
relates to https://github.com/crealytics/spark-excel/issues/596

### CODE REVIEW

**Comment by flo076** [comment]
Hello, @pjfanning ,

i think log4j-api should be shaded included on the fat jar and shade. 

Do you agree ?

**Comment by pjfanning** [comment]
I think all the jars I listed should be in the fat jar - including log4j-api - but I'm waiting for @nightscape 's input about whether adding additional jars is ok

**Comment by nightscape** [comment]
@pjfanning adding additional jars to the fat jar is ok from my side.
I think/hope, jar size is not a huge constraint in the context of Spark.
I've been fat-jar-adding and shading dependencies on a trial-and-error basis, not sure if there's a more principled way to do this.
If you think this is ready to try, I could either merge it to `main` and do a pre-release, or try to cut a pre-release from a branch.

**Comment by nightscape** [comment]
@pjfanning I think I can only do a pre-release for branches of this repo. I've given you write permission, would it be possible to rebase your changes on the latest `main` and create a new PR directly to this repo (i.e. adding this repo as a remote and pushing your changes to a new branch here)?
Unfortunately, there's also general problems with the build right now which I haven't been able to resolve yet, but I'd do a pre-release as soon as I get the build to work again.

**Comment by pjfanning** [comment]
@nightscape I created #620 off a branch that is now on this repo as opposed to my fork repo

**Pull request closed without merging**
