### PR TITLE
fix for https://github.com/crealytics/spark-excel/issues/480

### PR DESCRIPTION
**Pull request by cristichircu**
create a new pull request with suggestions from https://github.com/crealytics/spark-excel/pull/491

### CODE REVIEW

**Comment by cristichircu** [comment]
@nightscape Is this what you had in mind?
I was thinking about making a similar change for v1 and adding a configureProviders method and calling it before [workbook reader initialization](https://github.com/crealytics/spark-excel/blob/07aea8290e9cd9797b7320fb44121929ca225021/src/main/scala/com/crealytics/spark/excel/DefaultSource.scala#L22) or in [withWorkbook](https://github.com/crealytics/spark-excel/blob/07aea8290e9cd9797b7320fb44121929ca225021/src/main/scala/com/crealytics/spark/excel/WorkbookReader.scala#L15). Thoughts?

Thnks!

**Comment by nightscape** [comment]
That's exactly what I had in mind 👍 
I would say the workbook reader initialisation would be a good place.

**Comment by cristichircu** [comment]
looks like we're running into some ConcurrentModificationExceptions caused by removeIf. Do you think it’s worth synchronizing this? I would revert to the initial version (like it is for v1)

**Comment by nightscape** [comment]
Can you maybe try putting it at the [start of `createRelation`](https://github.com/crealytics/spark-excel/blob/07aea8290e9cd9797b7320fb44121929ca225021/src/main/scala/com/crealytics/spark/excel/DefaultSource.scala#L22)?
Afaik, this method only gets called when a `spark.read.format("excel")` is being run.
The `synchronized` might still make sense though if `read` is called in parallel.

**Comment by cristichircu** [comment]
The ConcurrentModificationException was for v2. If I understand correctly your suggestion is only applicable for v1.
Should I understand that v2 is ok the way it is and your suggestion is related to [my comment](https://github.com/crealytics/spark-excel/pull/513#issuecomment-1009785825) earlier regarding the proposed changed for v1?

**Comment by nightscape** [comment]
Ah sorry, confusion from my side. I thought there is a `createRelation` in v2 as well.
I'm not yet familiar with the v2 implementation as this was done by @quanghgx.
@quanghgx would you know a good place where the registration of `WorkbookFactory`s could be done in v2?
Best in a method that does not get called too often / concurrently.

**Comment by cristichircu** [comment]
@quanghgx can you please share your thougths on this when you get a chance? Thank you!

**Comment by quanghgx** [comment]
Hi @nightscape and @cristichircu 
Sorry for missing this thread. Let me double check and get back to you two this weekend.
Sincerely,

**Comment by cristichircu** [comment]
Hi @quanghgx ! Did you get a chance to have a look at this? Thanks!

**Comment by quanghgx** [comment]
Hi @nightscape and @cristichircu 
1+ with v2/excel/ExcelHelper.scala, this seems the most practical position to put this initialization.
Sincerely,

**Pull request merged**
