### PR TITLE
Make safe header

### PR DESCRIPTION
**Pull request by davidw76**
Automatically avoid duplicate column names
copied from [spark-csv](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/csv/CSVDataSource.scala)

### CODE REVIEW

**Comment by nightscape** [comment]
Hi David, the Travis error seems unrelated.
Could you rebase the PR on the latest master instead of merging and then push force? That should also trigger a new build which will hopefully succeed.

**Comment by davidw76** [comment]
Not sure what is wrong.. the build has been running 40+ minutes

**Comment by davidw76** [comment]
looks like it timed out

**Comment by nightscape** [comment]
Hey David, could you rebase on the latest master again and push force?
I updated SBT to 1.1.0 and the corresponding build is green, so hopefully yours will be, too.

**Comment by davidw76** [comment]
looks like the build is good now

**Pull request merged**
