### PR TITLE
added executor-base data source.

### PR DESCRIPTION
**Pull request by dmytroDragan**
Added as another source  executor-base data source. Extract common excel processing logic.

### CODE REVIEW

**Comment by nightscape** [comment]
Hi @3Dragan,

thanks for creating this PR! May I ask you to nonetheless to minimize the changeset (and rebase on the latest master)?
It's a hard to review the actual logic change as you moved a lot of code and changed the formatting.
I'm not opposed to doing refactorings, but would like to review them separately.

Thanks!

**Comment by 3Dragan** [comment]
Hi, I have reset origin parts of upstream.

**Comment by nightscape** [comment]
@3Dragan are you still interested in this?
If so, would you be so kind to create a version of this PR with a more minimal changeset?
It's really hard to review like that because we'd almost have to go through every file line by line and check if you changed something there or just moved the code to another location...

**Comment by nightscape** [comment]
The code has changed quite a bit in the mean time. I've got a branch which switches to Excel being a `FileFormat` which is how Spark's internal CSV reader is implemented as well.

**Pull request closed without merging**
